### ISSUE TITLE
urgent .net Quratz suddenly stop fire triggers simple and cron 

### ISSUE THREAD

**Issue by omrikaufman** [quartz-scheduler/quartz#1081]
this is the exception i am getting 
and this happened suddenly 
I am using nugget package for ,net 3.2.2
and using PostgresSQL version 4.26
and using nlog for loggging
can someone help :)

2023-11-08 14:38:56.0043,13,Debug,Quartz.Core.JobRunShell,Calling Execute on job MigrationPlans/11107-A.MigrationPlans/11107-A-Job-,
2023-11-08 14:38:56.0043,13,Error,Quartz.Core.JobRunShell,Job MigrationPlans/11107-A.MigrationPlans/11107-A-Job- threw an unhandled Exception: ,"System.InvalidOperationException Not a recovering job    at Quartz.Impl.JobExecutionContextImpl.get_RecoveringTriggerKey()
   at System.Diagnostics.DiagnosticSourceEventSource.TransformSpec.PropertySpec.PropertyFetch.RefTypedFetchProperty`2.Fetch(Object obj)
   at System.Diagnostics.DiagnosticSourceEventSource.TransformSpec.Morph(Object obj)
   at System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform.Morph(Object args)
   at System.Diagnostics.DiagnosticSourceEventSource.FilterAndTransform.<>c__DisplayClass2_1.<.ctor>b__2(KeyValuePair`2 evnt)
   at System.Diagnostics.DiagnosticSourceEventSource.CallbackObserver`1.OnNext(T value)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at System.Diagnostics.DiagnosticSource.StartActivity(Activity activity, Object args)
   at Quartz.Logging.JobDiagnosticsWriter.WriteStarted(IJobExecutionContext context, DateTimeOffset startTimeUtc)
   at Quartz.Core.JobRunShell.<Run>d__10.MoveNext()"

**Comment by jonnybecker** [comment]
This is Quartz for Java, your question refers to .Net. You might want to ask your question here: https://github.com/quartznet/quartznet

Please close this question.

**Comment by t-beckmann** [comment]
@omrikaufman see above, please close this question.
