### ISSUE TITLE
Empty Scheduler.getTriggersOfJob(JobKey) throws IndexOutOfBoundsException (not SchedulerException)

### ISSUE THREAD

**Issue by AdamDanischewski** [quartz-scheduler/quartz#1103]
Using Quartz 2.3.2 

Scheduler.getTriggersOfJob(JobKey) is advertised to possibly throw SchedulerException. Yet if jobkey is not a hit or if there are no triggers instead I get: 
```
[INFO ] 2024-02-18 12:55:00.547 [https-jsse-nio-8085-exec-9] it.test.procrun.QuartzRestController.printJobTriggers(QuartzRestController.java:370) - Inside with schduler: schedulerFactoryBean
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.base/java.util.LinkedList.checkElementIndex(LinkedList.java:559)
	at java.base/java.util.LinkedList.get(LinkedList.java:480)
	at it.test.procrun.QuartzRestController.printJobTriggers(QuartzRestController.java:377)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at org.springframework.web.
```

**Comment by AdamDanischewski** [comment]
My bad, it works fine - I had an info statement that was triggering it below.
