### ISSUE TITLE
after a few days(1 or 2 days), Quartz will throw a Exception named NoClassDefFoundError

### ISSUE THREAD

**Issue by cyssxt** [quartz-scheduler/quartz#122]
hello!My version is 2.1.7
The info below:
2017-04-06 00:35:00,014 [DefaultQuartzScheduler_Worker-5] ERROR org.quartz.core.JobRunShell              -Job group1.day_crotab threw an unhandled Exception: 
java.lang.NoClassDefFoundError: org/apache/ibatis/reflection/ExceptionUtil
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:362)
        at com.sun.proxy.$Proxy212.selectOne(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:159)
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:68)
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)
        at com.sun.proxy.$Proxy221.selectCityCode(Unknown Source)
        at com.cyssxt.service.impl.ConfigServiceImpl.grapDataByScenic(ConfigServiceImpl.java:510)
        at com.cyssxt.job.QuartzJob.execute(QuartzJob.java:63)
        at com.cyssxt.job.QuartzJobProxy.execute(QuartzJobProxy.java:16)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
2017-04-06 00:35:03,706 [DefaultQuartzScheduler_Worker-5] ERROR org.quartz.core.ErrorLogger              -Job (group1.day_crotab threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.NoClassDefFoundError: org/apache/ibatis/reflection/ExceptionUtil]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:224)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: java.lang.NoClassDefFoundError: org/apache/ibatis/reflection/ExceptionUtil
        at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:362)
        at com.sun.proxy.$Proxy212.selectOne(Unknown Source)
        at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:159)
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:68)
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)
        at com.sun.proxy.$Proxy221.selectCityCode(Unknown Source)
        at com.cyssxt.service.impl.ConfigServiceImpl.grapDataByScenic(ConfigServiceImpl.java:510)
        at com.cyssxt.job.QuartzJob.execute(QuartzJob.java:63)
        at com.cyssxt.job.QuartzJobProxy.execute(QuartzJobProxy.java:16)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)

Also,I meet a question for 3-4 times! When use Quartz with mybaits,a few days later,it will lose connection with mysql for reason DataSource is Closed!I will push the log if i meet it next time!
My English is pool! You can contact with me by email(cyssxt@163.com)

**Comment by jhouserizer** [comment]
There must be something in your application's classloader setup that goes into a bad state after those few days.  It's hard for me to even make any guess at what that might be.   But the error is clearly related to availability of class definitions from the class loader.

My only suggestion would be to try some different Quartz settings related to classloaders - because users have in the past had problems in some container environments there are a couple config options to tell Quartz to switch between using the default class loader (from the class/thread) and from the thread that initialized Quartz in the first place.  http://www.quartz-scheduler.org/documentation/quartz-2.2.x/configuration/ConfigMain.html

**Comment by cyssxt** [comment]
Thanks!

**Comment by cyssxt** [comment]
Thanks!I will try!

**Comment by adityaburra** [comment]
@cyssxt - I too am facing similar issue, did you manage to get it working?

**Comment by cyssxt** [comment]
Maybe when i use thread.stop() to stop a thread,this will take classloader goes into a bad state! Remove it and use while(flag) replace it! The problem does not happen again!

**Comment by cyssxt** [comment]
@adityaburra

**Comment by zemian** [comment]
Closing outdated, unresolved issues. Please, reopen if still relevant.

**Comment by ankitsinghal1234** [comment]
This issue still exists I am facing it in my application.

**Comment by kbuchiveeram** [comment]
I am also getting the same issue in production, we are using weblogic server. Please help me. we are using old version of the  quartz 1.7.3

**Comment by kbuchiveeram** [comment]
> 

Is this issue fixed?
