### ISSUE TITLE
QRTZ_SIMPROP_TRIGGERS record was deleted

### ISSUE THREAD

**Issue by glind98** [quartz-scheduler/quartz#138]
We are using the quartz scheduler in our java web app. We are using version 2.2.1. We have had a bug occur twice where the trigger record has been removed from the QRTZ_SIMPROP_TRIGGERS table. This is causing jobs to stop running. We are going to upgrade to the latest version but there is no indication that this was fixed. This is an issue that we can not re-create at will. We deleted the trigger from the QRTZ_TRIGGERS table to fix the problem, but we cannot expect customers to do this.

Here is the stack trace, the error is misleading.  The record cannot be found in the QRTZ_SIMPROP_TRIGGERS table.  There is a bug in the error message (it says QRTZ_SIMPLE_TRIGGERS).

2017-04-18 00:01:38,685 ERROR org.quartz.impl.jdbcjobstore.JobStoreTX MisfireHandler: Error handling misfires: Couldn't retrieve trigger: No record found for selection of Trigger with key: 'DEFAULT.Delete PS Audit logs' and statement: SELECT * FROM QRTZ_SIMPLE_TRIGGERS WHERE SCHED_NAME = 'MFTScheduler' AND TRIGGER_NAME = ? AND TRIGGER_GROUP = ?
org.quartz.JobPersistenceException: Couldn't retrieve trigger: No record found for selection of Trigger with key: 'DEFAULT.Delete PS Audit logs' and statement: SELECT * FROM QRTZ_SIMPLE_TRIGGERS WHERE SCHED_NAME = 'MFTScheduler' AND TRIGGER_NAME = ? AND TRIGGER_GROUP = ? [See nested exception: java.lang.IllegalStateException: No record found for selection of Trigger with key: 'DEFAULT.Delete PS Audit logs' and statement: SELECT * FROM QRTZ_SIMPLE_TRIGGERS WHERE SCHED_NAME = 'MFTScheduler' AND TRIGGER_NAME = ? AND TRIGGER_GROUP = ?]
    at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveTrigger(JobStoreSupport.java:1533)
    at org.quartz.impl.jdbcjobstore.JobStoreSupport.recoverMisfiredJobs(JobStoreSupport.java:979)
    at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3187)
    at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:3935)
    at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:3956)
Caused by: java.lang.IllegalStateException: No record found for selection of Trigger with key: 'DEFAULT.Delete PS Audit logs' and statement: SELECT * FROM QRTZ_SIMPLE_TRIGGERS WHERE SCHED_NAME = 'MFTScheduler' AND TRIGGER_NAME = ? AND TRIGGER_GROUP = ?
    at org.quartz.impl.jdbcjobstore.SimplePropertiesTriggerPersistenceDelegateSupport.loadExtendedTriggerProperties(SimplePropertiesTriggerPersistenceDelegateSupport.java:157)
    at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectTrigger(StdJDBCDelegate.java:1819)
    at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveTrigger(JobStoreSupport.java:1531)

**Comment by wwuddan123** [comment]
`	@Bean
	public  SchedulerFactoryBean schedulerFactoryBean() {
		final SchedulerFactoryBean schedulerFactoryBean = new SchedulerFactoryBean();
		schedulerFactoryBean.setDataSource(dataSource());
		**schedulerFactoryBean.setTransactionManager(new DataSourceTransactionManager(dataSource()));**//maybe you need this line
		return schedulerFactoryBean;
	}`

**Comment by IbrahimImran** [comment]
What is the expansion of qrtz_simprop_triggers?

**Comment by rxxy** [comment]
+1

This error occurs when the `qrtz_triggers` table has a trigger record, but the `qrtz_simple_triggers` table does not have the record, and quartz wants to load the extended attributes of the simple trigger.

I added a lot of tasks from SimpleTrigger, a lot of this error occurred

**Comment by rxxy** [comment]
quartz version is 2.3.2

**Comment by Lsn12138** [comment]
请问一下最后这个问题是怎么解决的，我现在也遇到了这个问题

**Comment by JiangPang0723** [comment]
> 请问一下最后这个问题是怎么解决的，我现在也遇到了这个问题

I don't know what you're talking about
