### ISSUE TITLE
In cluster mode,when acquireNextTrigger throw NPE

### ISSUE THREAD

**Issue by zhouze1992** [quartz-scheduler/quartz#174]
quartz.version=2.3.0
In cluster mode, there are two hosts in my cluster.I use quartz to schedule more than 200 jobs per second(use simple trigger).
During the job scheduling, two hosts in the cluster will throw a NPE.
According to my local debugging, in the line code in JobStoreSupport.java:2883 nextTrigger.getNextFireTime () is null, so call the getTime () method to throw an exception.
The following is an exception message:
ERROR --- [SchedulerThread] org.quartz.core.ErrorLogger              : An error occurred while scanning for the next triggers to fire.

org.quartz.JobPersistenceException: Couldn't acquire next trigger: null
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2910) ~[quartz-2.3.0.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2805) ~[quartz-2.3.0.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2803) ~[quartz-2.3.0.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3849) ~[quartz-2.3.0.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2802) ~[quartz-2.3.0.jar:na]
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:287) ~[quartz-2.3.0.jar:na]
Caused by: java.lang.NullPointerException: null
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2883) ~[quartz-2.3.0.jar:na]
	... 5 common frames omitted

**Comment by zhouze1992** [comment]
use
org.quartz.jobStore.acquireTriggersWithinLock=true
or
set
org.quartz.scheduler.batchTriggerAcquisitionMaxCount more than 1
