### ISSUE TITLE
Quartz 2.2.3 stop schedule next job after some time

### ISSUE THREAD

**Issue by anxiaoyi** [quartz-scheduler/quartz#276]
Quartz 2.2.3 stop schedule next job after some time, from the thread dump, we can know all Worker in TIMED_WAITING state (waiting runnable), but the QuartzSchedulerThread are block for available threads:

My Job was used to download files, possible 1MB ~ 1GB size. some times I will find the following error from the logs:

```
[2018-11-09 00:11:25.591] [ERROR] [downloaderScheduler_Worker-10] SimpleThreadPool Worker thread was interrupt()'ed.
java.lang.InterruptedException: null
        at java.lang.Object.wait(Native Method)
```

Here is a thread dump:

```
"downloaderScheduler_QuartzSchedulerThread" #48 prio=5 os_prio=0 tid=0x00007fdd8d2c3000 nid=0x5a in Object.wait() [0x00007fdc1b9f8000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool.blockForAvailableThreads(SimpleThreadPool.java:452)
	- locked <0x000000008024be18> (a java.lang.Object)
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:263)

"downloaderScheduler_Worker-10" #47 prio=5 os_prio=0 tid=0x00007fdd8d2c1800 nid=0x59 in Object.wait() [0x00007fdc1baf9000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
	- locked <0x0000000080219190> (a java.lang.Object)

"downloaderScheduler_Worker-9" #46 prio=5 os_prio=0 tid=0x00007fdd8d2bf800 nid=0x58 in Object.wait() [0x00007fdc1bbfa000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
	- locked <0x0000000080219330> (a java.lang.Object)

"downloaderScheduler_Worker-8" #45 prio=5 os_prio=0 tid=0x00007fdd8d2be000 nid=0x57 in Object.wait() [0x00007fdc1bcfb000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
	- locked <0x00000000802194d0> (a java.lang.Object)

"downloaderScheduler_Worker-7" #44 prio=5 os_prio=0 tid=0x00007fdd8d2bc800 nid=0x56 in Object.wait() [0x00007fdc1bdfc000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
	- locked <0x0000000080219670> (a java.lang.Object)

"downloaderScheduler_Worker-6" #43 prio=5 os_prio=0 tid=0x00007fdd8d2ba800 nid=0x55 in Object.wait() [0x00007fdc13dfc000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
	- locked <0x0000000080244d40> (a java.lang.Object)

"downloaderScheduler_Worker-5" #42 prio=5 os_prio=0 tid=0x00007fdd8d2b9000 nid=0x54 in Object.wait() [0x00007fdc1befd000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
	- locked <0x0000000080219810> (a java.lang.Object)

"downloaderScheduler_Worker-4" #41 prio=5 os_prio=0 tid=0x00007fdd8d2b7000 nid=0x53 in Object.wait() [0x00007fdc1bffe000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
	- locked <0x0000000080244ee0> (a java.lang.Object)

"downloaderScheduler_Worker-3" #40 prio=5 os_prio=0 tid=0x00007fdd8d2b5800 nid=0x52 in Object.wait() [0x00007fdcb8192000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
	- locked <0x00000000802440c8> (a java.lang.Object)

"downloaderScheduler_Worker-2" #39 prio=5 os_prio=0 tid=0x00007fdd8d2b2000 nid=0x51 in Object.wait() [0x00007fdcb8293000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
	- locked <0x0000000080245080> (a java.lang.Object)

"downloaderScheduler_Worker-1" #38 prio=5 os_prio=0 tid=0x00007fdd8d2b0000 nid=0x50 in Object.wait() [0x00007fdcb8394000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:568)
	- locked <0x0000000080244268> (a java.lang.Object)
```

**Comment by jarlah** [comment]
This issue was moved to OpenQuartz/quartz-scheduler#4

**Comment by zemian** [comment]
It would be hard to help you debug this since we don't know what your job is doing. I suspect that your job might be taking too long that block up all the threads in scheduler. Try to ensure your single job successfully and ensure there is enough time and threads to run them all.

**Comment by anxiaoyi** [comment]
@zemian Hi zemian, Thank you for your reply. My job was used to download files, which size about 1MB ~ 1GB. logic like this:

``` Java
DownloadResult result = createResult();

try {
    result = downloadFile("http://abc.com/file");
} catch (InterruptedException e) {
    result.setException(e);
} catch (IOException e) {
    result.setException(e);
} catch (Exception e) {
    result.setException(e);
}

// ======================
// downloadFile contains some code like this
// ======================

private long copyInterruptibly(InputStream is, FileOutputStream os, HttpRequest request)
    throws IOException {
    // ...
    
    for (count = 0L; -1 != (n = is.read(buffer)); count += (long)n) {
        // Handle Ctrl-C
        if (Thread.currentThread.isInterrupted()) {
            request.abort();
        }

        throw new InterruptedException();

        os.write(buffer, 0, n);
    }

    return count;
}
```
I catched all the exception which `downloadFile` method throwed, and if the download job are blocking threads, why all `Worker` thread state are in `TIMED_WAITING` state, It should be in `RUNNABLE` state. And the problem is hard to recurrence，I got no idea to how to find and fix this bug.

**Comment by zemian** [comment]
Unfortunately I can't help debug the job your are writing about. You would have to write a test case to prove Quartz is misbehaving in order for me to fix it. Please investigate on your own code and come up with a standalone test case if possible.

**Comment by zemian** [comment]
Closing outdated, unresolved issues. Please, reopen if still relevant.
