### ISSUE TITLE
Quartz+PostgreSQL = Couldn't acquire trigger: Couldn't retrieve trigger: Bad value for type long \x

### ISSUE THREAD

**Issue by mduruisseau** [quartz-scheduler/quartz#284]
Hello,

I have an application working with spring-boot and the quartz-starter.
Everything works perfectly with the in memory storage, but when I want to use my database (**PostgreSQL**) I get this error : 
```
org.quartz.JobPersistenceException: Couldn't acquire next trigger: Couldn't retrieve trigger: Bad value for type long : \x
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2910) ~[quartz-2.3.0.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2805) ~[quartz-2.3.0.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2803) ~[quartz-2.3.0.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3849) ~[quartz-2.3.0.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2802) ~[quartz-2.3.0.jar:?]
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:287) [quartz-2.3.0.jar:?]
Caused by: org.quartz.JobPersistenceException: Couldn't retrieve trigger: Bad value for type long : \x
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveTrigger(JobStoreSupport.java:1538) ~[quartz-2.3.0.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2854) ~[quartz-2.3.0.jar:?]
	... 5 more
Caused by: org.postgresql.util.PSQLException: Mauvaise valeur pour le type long : \x
	at org.postgresql.jdbc.PgResultSet.toLong(PgResultSet.java:2869) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgResultSet.getLong(PgResultSet.java:2093) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgResultSet.getBlob(PgResultSet.java:419) ~[postgresql-42.2.2.jar:42.2.2]
	at org.postgresql.jdbc.PgResultSet.getBlob(PgResultSet.java:406) ~[postgresql-42.2.2.jar:42.2.2]
	at com.zaxxer.hikari.pool.HikariProxyResultSet.getBlob(HikariProxyResultSet.java) ~[HikariCP-2.7.9.jar:?]
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.getObjectFromBlob(StdJDBCDelegate.java:3190) ~[quartz-2.3.0.jar:?]
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectTrigger(StdJDBCDelegate.java:1780) ~[quartz-2.3.0.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retrieveTrigger(JobStoreSupport.java:1536) ~[quartz-2.3.0.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2854) ~[quartz-2.3.0.jar:?]
	... 5 more
```

application.properties : 

```
## QuartzProperties
spring.quartz.job-store-type = jdbc
spring.quartz.properties.org.quartz.threadPool.threadCount = 2
spring.quartz.jdbc.initialize-schema=always
org.quartz.jobStore.driverDelegateClass = org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
```

I tried a lot of configuration, db schema, ... but nothing works.
Could you help me ?

**Comment by Tinet-lizy** [comment]
if you use spring boot ,please use
**spring.quartz.properties.org.quartz.jobStore.driverDelegateClas=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate**

hope help you

**Comment by zemian** [comment]
Close as not an issue

**Comment by najmul-csebuet** [comment]
There is a type in above comment. It should be Class not Clas
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate

**Comment by pabloilich-grupoassa** [comment]
Hi Guys, i am having the same issue, i am using the following configuration.

org.quartz.scheduler.instanceName=queryBuilderApp
org.quartz.scheduler.instanceId=AUTO
##number of concurrent jobs that can be run.
org.quartz.threadPool.threadCount=5
org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
#spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
org.quartz.jobStore.useProperties=true
## //if job is delayed by 1 minute, don't consider it as misfire.
org.quartz.jobStore.misfireThreshold=60000
org.quartz.jobStore.isClustered=false
org.quartz.plugin.shutdownHook.class=org.quartz.plugins.management.ShutdownHookPlugin
org.quartz.plugin.shutdownHook.cleanShutdown=TRUE

Gradle File
	compile "org.quartz-scheduler:quartz"
	compile "org.quartz-scheduler:quartz-jobs"
	
Thanks !!

**Comment by VigneshIyappan** [comment]
I faced the same issue. I have used PostgresSqlDelegate as my delegate class. But the same error occurs.

**Comment by eug3nio** [comment]
@VigneshIyappan 

https://stackoverflow.com/a/51403990

**Comment by hasanli-orkhan** [comment]
I faced the same issue.
Here is the config file:
```
spring:
  quartz:
  job-store-type: jdbc
  jdbc:
    schema: classpath:db/quartz_tables.sql
  properties:
    org:
      quartz:
        scheduler:
          instanceName: quartzScheduler
          skipUpdateCheck: true
        dataSource:
          quartzDataSource:
            driver: org.postgresql.Driver
            URL: jdbc:postgresql://localhost:5432/test
            user: postgres
            password: postgres
            maxConnections: 30
            provider: hikaricp
        jobStore:
          isClustered: false
          useProperties: false
#            class: org.springframework.scheduling.quartz.JobStoreCMT
          class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
          driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
          dataSource: quartzDataSource
          tablePrefix: qrtz_
          misfireThreshold: 60000
        threadPool:
          class: org.quartz.simpl.SimpleThreadPool
          threadCount: 30
          threadPriority: 5
          threadsInheritContextClassLoaderOfInitializingThread: true
```
When i'm using PostgreSQLDelegate Trigger records in triggers table not created. Only qrtz_job_details is filled.
When I'm using StdJDBCDelegate Trigger records is filled too, but I'm getting exception:
`Couldn't acquire trigger: Couldn't retrieve trigger: Bad value for type long \x`
Also tried this approach - https://stackoverflow.com/a/51403990

**Comment by undisputedashu** [comment]
I was having the same issue finally fixed it. https://stackoverflow.com/a/74378819/4765105 refer this link for details
@Bean
public Properties quartzProperties() throws IOException {
    PropertiesFactoryBean propertiesFactoryBean = new PropertiesFactoryBean();
    propertiesFactoryBean.setLocation(new ClassPathResource("application.properties"));
    Properties props = new Properties();
    props.put("org.quartz.jobStore.driverDelegateClass", "org.quartz.impl.jdbcjobstore.PostgreSQLDelegate");
    propertiesFactoryBean.setProperties(props);
    propertiesFactoryBean.afterPropertiesSet();
    return propertiesFactoryBean.getObject();
}
