### ISSUE TITLE
rg.quartz.SchedulerException: Job instantiation failed

### ISSUE THREAD

**Issue by Tinet-lizy** [quartz-scheduler/quartz#285]
spring boot 2.0.4 RELEASE，quartz,exception on shedule

org.quartz.SchedulerException: Job instantiation failed
	at org.springframework.scheduling.quartz.AdaptableJobFactory.newJob(AdaptableJobFactory.java:47)
	at org.quartz.core.JobRunShell.initialize(JobRunShell.java:127)
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:392)
Caused by: java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at org.springframework.context.support.ApplicationListenerDetector.postProcessAfterInitialization(ApplicationListenerDetector.java:73)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:439)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1712)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:415)
	at org.springframework.boot.autoconfigure.quartz.AutowireCapableBeanJobFactory.createJobInstance(AutowireCapableBeanJobFactory.java:45)
	at org.springframework.scheduling.quartz.AdaptableJobFactory.newJob(AdaptableJobFactory.java:43)
	... 2 common frames omitted

**Comment by zemian** [comment]
Hi there, please provide more info with your issue. What you provided is not enough to tell it's Quartz problem.

**Comment by Tinet-lizy** [comment]
I use spring boot2.0.4 and quartz and Postresql ,this issues find in spring boot 2.0.4 but 2.1.0 is ok

**Comment by zemian** [comment]
Close as not an issue
