### ISSUE TITLE
transaction error occurred in mysql group replication(multi master mode)

### ISSUE THREAD

**Issue by humbinal** [quartz-scheduler/quartz#288]
such as the error log:

SchedulerListener: Scheduler error msg is An error occurred while scanning for the next triggers to fire., for {}

org.quartz.JobPersistenceException: Couldn't commit jdbc connection. Plugin instructed the server to rollback the current transaction.
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.commitConnection(JobStoreSupport.java:3734)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3851)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2802)
        at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:287)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Plugin instructed the server to rollback the current transaction.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.Util.getInstance(Util.java:408)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:952)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2482)
        at com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1547)
        at com.mysql.jdbc.MultiHostMySQLConnection.commit(MultiHostMySQLConnection.java:129)
        at sun.reflect.GeneratedMethodAccessor236.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.mysql.jdbc.FailoverConnectionProxy.invokeMore(FailoverConnectionProxy.java:493)
        at com.mysql.jdbc.MultiHostConnectionProxy.invoke(MultiHostConnectionProxy.java:468)
        at com.sun.proxy.$Proxy148.commit(Unknown Source)
        at com.alibaba.druid.filter.FilterChainImpl.connection_commit(FilterChainImpl.java:199)
        at com.alibaba.druid.filter.FilterAdapter.connection_commit(FilterAdapter.java:781)
        at com.alibaba.druid.filter.FilterChainImpl.connection_commit(FilterChainImpl.java:194)
        at com.alibaba.druid.filter.stat.StatFilter.connection_commit(StatFilter.java:267)
        at com.alibaba.druid.filter.FilterChainImpl.connection_commit(FilterChainImpl.java:194)
        at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.commit(ConnectionProxyImpl.java:123)
        at com.alibaba.druid.pool.DruidPooledConnection.commit(DruidPooledConnection.java:749)
        at sun.reflect.GeneratedMethodAccessor236.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.invoke(AttributeRestoringConnectionInvocationHandler.java:73)
        at com.sun.proxy.$Proxy256.commit(Unknown Source)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.commitConnection(JobStoreSupport.java:3732)
        ... 3 common frames omitted

**Comment by zemian** [comment]
Hi, can you post more information to replicate this error? Give the quartz.properties and describe your DB setup. If you can please try to provide a standalone repeatable test case.

**Comment by zemian** [comment]
Close for inactivity

**Comment by dovanvu1792** [comment]
Close for inactivity =))
