### ISSUE TITLE
Quartz fails to startup against DB with RECOVERING_JOBS triggers

### ISSUE THREAD

**Issue by buckett** [quartz-scheduler/quartz#35]
We were testing an upgrade of quartz in another product and we started off with a DB dump of the live data, then we ran the migrations to upgrade it to the schema required by quartz 2.2.2 and then when attempting to startup the application (and quartz) we would hit a NullPointerException:

```
2016-07-13 13:19:33,978 [QuartzScheduler_QuartzSchedulerThread] ERROR org.quartz.core.ErrorLogger - An error occurred while scanning for the next triggers to fire.
org.quartz.JobPersistenceException: Couldn't acquire next trigger: null [See nested exception: java.lang.NullPointerException]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2860)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$40.execute(JobStoreSupport.java:2759)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$40.execute(JobStoreSupport.java:2757)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3799)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2756)
        at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:272)
Caused by: java.lang.NullPointerException
        at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.insertFiredTrigger(StdJDBCDelegate.java:2651)
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2844)
        ... 5 more
```

This looks to be because we had a RECOVERING_JOBS trigger in the database from the dump and these don't have a next fire time which `acquireNextTrigger` method was expecting. By dropping this row from the DB quartz started up correctly, however it would be good if quartz was a little more robust.

**Comment by buckett** [comment]
The DB dump was quartz 1.8.6 and the new version of quartz was 2.2.2. I also reported an issue in the other product (https://jira.sakaiproject.org/browse/SAK-31500).

**Comment by jhouserizer** [comment]
I studied through this, and can't find a simple solution for making it "a little more robust".

It wouldn't be terribly hard to find the specific problem that led to the exception here, and trap for it, but to catch  similar (but different) problems generally will be more than a little work, and a bit tricky so as to distinguish those from transient problems (such as losing db connectivity when trying to do the insert).
