### ISSUE TITLE
Error scheduling jobs:Job class must implement the Job interface.

### ISSUE THREAD

**Issue by Machars** [quartz-scheduler/quartz#36]
#  this is the happen: 
[org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin.processFile(XMLSchedulingDataProcessorPlugin.java:322)]  Error scheduling jobs: Job class must implement the Job interface.
java.lang.IllegalArgumentException: Job class must implement the Job interface.
	at org.quartz.JobDetail.setJobClass(JobDetail.java:291)
	at org.quartz.JobDetail.<init>(JobDetail.java:156)
	at org.quartz.xml.XMLSchedulingDataProcessor.process(XMLSchedulingDataProcessor.java:655)
	at org.quartz.xml.XMLSchedulingDataProcessor.processFile(XMLSchedulingDataProcessor.java:501)
	at org.quartz.xml.XMLSchedulingDataProcessor.processFileAndScheduleJobs(XMLSchedulingDataProcessor.java:841)
	at org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin.processFile(XMLSchedulingDataProcessorPlugin.java:317)
	at org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin.start(XMLSchedulingDataProcessorPlugin.java:245)
	at org.quartz.plugins.SchedulerPluginWithUserTransactionSupport.start(SchedulerPluginWithUserTransactionSupport.java:144)
	at org.quartz.core.QuartzScheduler.startPlugins(QuartzScheduler.java:2341)
	at org.quartz.core.QuartzScheduler.start(QuartzScheduler.java:514)
	at org.quartz.impl.StdScheduler.start(StdScheduler.java:143)
	at org.quartz.ee.servlet.QuartzInitializerServlet.init(QuartzInitializerServlet.java:184)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1282)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1195)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1085)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5318)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5610)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1259)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1998)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

here is my properties：
org.quartz.threadPool.class = org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.threadCount = 4
org.quartz.plugin.jobInitializer.class = org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin
org.quartz.plugin.jobInitializer.fileNames = quartz_jobs.xml

# and the xml file:
<?xml version="1.0" encoding="UTF-8"?>  
<job-scheduling-data xmlns="http://www.quartz-scheduler.org/xml/JobSchedulingData"  
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
xsi:schemaLocation="http://www.quartz-scheduler.org/xml/JobSchedulingData http://www.quartz-scheduler.org/xml/job_scheduling_data_1_8.xsd"  
version="1.8">  
<schedule>  
    <job>  
        <name>quartztest</name>  
        <group>quartzGroup</group>  
        <description>  
            this is HelloWorld......  
        </description>  
        <job-class>test.Quartztest</job-class>  
    </job>  
    <trigger>  
        <cron>  
            <name>quartztrigger</name>  
            <job-name>quartztest</job-name>
            <job-group>quartzGroup</job-group>  
            <cron-expression>0/10 * * * * ?</cron-expression>  
        </cron>  
    </trigger>  
</schedule>  
</job-scheduling-data>  

# my quartz class position :+1: 
src/test/Quartztest.java
 my pro environment :
jdk 1.7
quartz 1.8.6
quartz all 1.8.6
and some anthor jar file

when this in the new web project it working normally , but when i put it in my project ,it take the problem,
Any help will be greatly appreciate

**Comment by Machars** [comment]
i solved by change the eviroment!   but i don't what cause the problem.
