### ISSUE TITLE
HirariCP provider throws exception with "discardIdleConnectionsSeconds"

### ISSUE THREAD

**Issue by zemian** [quartz-scheduler/quartz#420]
Per documentation, we can use "discardIdleConnectionsSeconds" for provider "hikaricp", but setting this will throws exception error:

```
Exception in thread "main" org.quartz.SchedulerException: Could not initialize DataSource: quartzDataSource [See nested exception: java.lang.NoSuchMethodException: No setter for property 'discardIdleConnectionsSeconds']
	at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:1042)
	at org.quartz.impl.StdSchedulerFactory.getScheduler(StdSchedulerFactory.java:1567)
	at zemian.quartzstarter.QuartzServer.main(QuartzServer.java:25)
Caused by: java.lang.NoSuchMethodException: No setter for property 'discardIdleConnectionsSeconds'
	at org.quartz.impl.StdSchedulerFactory.setBeanProps(StdSchedulerFactory.java:1455)
	at org.quartz.impl.StdSchedulerFactory.populateProviderWithExtraProps(StdSchedulerFactory.java:1413)
	at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:1040)
	... 2 more
```

**Comment by zemian** [comment]
There is a workaround though. Disable "discardIdleConnectionsSeconds" and use "idleTimeout" instead.

```
#org.quartz.dataSource.NAME.discardIdleConnectionsSeconds = 0
org.quartz.dataSource.NAME.idleTimeout = 0
```

This has the same affect as "discardIdleConnectionsSeconds" is just a alias Quartz tries to set the actual "idleTimeout" properties for you.

**Comment by zemian** [comment]
More examples can be found here now: https://github.com/quartz-scheduler/quartz/wiki/How-to-Use-DB-Connection-Pool
