### ISSUE TITLE
Simple trigger is not triggered due to job persistence exception: Couldn't acquire next trigger: ERROR: prepared statement "S_1" does not exist

### ISSUE THREAD

**Issue by bcokca** [quartz-scheduler/quartz#447]
Some of the failed simple triggers were causing some issues and I tried to manually delete them from the database. I cleaned up all the tables starts with qrtz but still getting the error below:

```
! org.postgresql.util.PSQLException: ERROR: prepared statement "S_1" does not exist
! at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2284)
! at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2003)
! at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
! at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
! at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:161)
! at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
! at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
! at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
! at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectTriggerToAcquire(StdJDBCDelegate.java:2613)
! at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2798)
! ... 5 common frames omitted
! Causing: org.quartz.JobPersistenceException: Couldn't acquire next trigger: ERROR: prepared statement "S_1" does not exist
! at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2864)
! at org.quartz.impl.jdbcjobstore.JobStoreSupport$40.execute(JobStoreSupport.java:2759)
! at org.quartz.impl.jdbcjobstore.JobStoreSupport$40.execute(JobStoreSupport.java:2757)
! at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3803)
! at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2756)
! at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:272)
```

I have also tried to upgrade the quartz version after seeing this issue: https://github.com/quartz-scheduler/quartz/issues/145 I thought partly because the misfired jobs were in a some sort of deadlock. So this set of logs are keep repeating: 
```
DEBUG [2019-05-21 00:50:37,550] org.quartz.impl.jdbcjobstore.StdRowLockSemaphore: Lock 'TRIGGER_ACCESS' is desired by: QuartzScheduler_Scheduler-helpdesks-mbp-2.group.on1558399826299_MisfireHandler
DEBUG [2019-05-21 00:50:37,551] org.quartz.impl.jdbcjobstore.StdRowLockSemaphore: Lock 'TRIGGER_ACCESS' is being obtained: QuartzScheduler_Scheduler-helpdesks-mbp-2.group.on1558399826299_MisfireHandler
DEBUG [2019-05-21 00:50:37,560] org.quartz.impl.jdbcjobstore.StdRowLockSemaphore: Lock 'TRIGGER_ACCESS' given to: QuartzScheduler_Scheduler-helpdesks-mbp-2.group.on1558399826299_MisfireHandler
INFO  [2019-05-21 00:50:37,572] org.quartz.impl.jdbcjobstore.JobStoreTX: Handling 1 trigger(s) that missed their scheduled fire-time.
```

**Comment by varunmaurya** [comment]
did you get any solution for this?
