### ISSUE TITLE
StdSchedulerFactory ConcurrentModificationException reading system properties

### ISSUE THREAD

**Issue by davidmoten** [quartz-scheduler/quartz#474]
Using quartz 2.3.1 I get the following exception occasionally on startup of a webapp in Tomcat.

```
java.util.ConcurrentModificationException
        at java.util.Hashtable$Enumerator.next(Hashtable.java:1387)
        at java.util.Hashtable.putAll(Hashtable.java:523)
        at org.quartz.impl.StdSchedulerFactory.overrideWithSysProps(StdSchedulerFactory.java:495)
        at org.quartz.impl.StdSchedulerFactory.initialize(StdSchedulerFactory.java:472)
        at org.quartz.impl.StdSchedulerFactory.getScheduler(StdSchedulerFactory.java:1552)
```

This is due to `StdSchedulerFactory.overrideWithSysProps` which looks like this:

https://github.com/quartz-scheduler/quartz/blob/1ba8447fae062f241944bcc98ca30fa63a063304/quartz-core/src/main/java/org/quartz/impl/StdSchedulerFactory.java#L475-L496

By calling `putAll` the `entrySet()` iterator is  used on `System.getProperties()` which is not a thread-safe way of traversing System properties.

The fix would be to instead traverse the System properties by using the Enumeration `propertyNames()` and calling `getProperty` on each property name.

Happy to provide PR.

CC @SuperEventSteven

**Comment by davidmoten** [comment]
I've submitted a PR #475 for this one
