### ISSUE TITLE
NPE thrown when attempting to acquire next trigger

### ISSUE THREAD

**Issue by hoshposh** [quartz-scheduler/quartz#495]
## Usage scenario
In our situation within our application we create a number of Quartz triggers, but then the action is sometimes cancelled, and the triggers are deleted using `Scheduler.deleteJob()`. This causes a situation where the newly created triggers are being processed, and before that can be completed the triggers are deleted.

## Issue
We experience intermittent NullPointerExceptions (NPE) in the `org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger()` routine. There appears to be an assumption that the call to `retrieveJob()` will always result in a non-null instance.

## Proposal
Is it possible to add defensive code within the `acquireNextTrigger()` to confirm that `job` is a valid instance, to handle this situation?

## Stacktrace
```
org.quartz.JobPersistenceException: Couldn't acquire next trigger: null [See nested exception: java.lang.NullPointerException]
  at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2923)
  at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2805)
  at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2803)
  at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3864)
  at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2802)
  at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:287)
Caused by: java.lang.NullPointerException
  at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2875)
  ... 5 more
```

**Comment by jhouserizer** [comment]
Which database is this occurring with?  With a cursory review, that sounds like transaction atomicity/isolation isn't being honored properly.

**Comment by hoshposh** [comment]
This occurred in postgres 10.1 for myself. However, I have not been able to consistently reproduce this problem I am sorry to say, but this was originally found from other team members about a year ago.

**Comment by dstarcev** [comment]
Apparently, there is a race condition in JobStoreSupport.acquireNextTrigger method which causes exceptions at several places when running in cluster mode. These are the ones I have met with postgresql 10.5:

1. [NPE](https://github.com/quartz-scheduler/quartz/blob/v2.3.2/quartz-core/src/main/java/org/quartz/impl/jdbcjobstore/JobStoreSupport.java#L2875) when the has already been deleted by another instance by the time we read it
2. [IllegalStateException](https://github.com/quartz-scheduler/quartz/blob/v2.3.2/quartz-core/src/main/java/org/quartz/impl/jdbcjobstore/StdJDBCDelegate.java#L1822) when the trigger extension has been deleted  (or has not been added) by another instance by the time we read it (and the trigger itself has not)

It is not clear to me what was supposed to prevent such a behavior with the default config values:
org.quartz.jobStore.acquireTriggersWithinLock=false
org.quartz.jobStore.txIsolationLevelSerializable=false

**Comment by jruivo-dev** [comment]
> Apparently, there is a race condition in JobStoreSupport.acquireNextTrigger method which causes exceptions at several places when running in cluster mode. These are the ones I have met with postgresql 10.5:
> 
> 1. [NPE](https://github.com/quartz-scheduler/quartz/blob/v2.3.2/quartz-core/src/main/java/org/quartz/impl/jdbcjobstore/JobStoreSupport.java#L2875) when the has already been deleted by another instance by the time we read it
> 2. [IllegalStateException](https://github.com/quartz-scheduler/quartz/blob/v2.3.2/quartz-core/src/main/java/org/quartz/impl/jdbcjobstore/StdJDBCDelegate.java#L1822) when the trigger extension has been deleted  (or has not been added) by another instance by the time we read it (and the trigger itself has not)
> 
> It is not clear to me what was supposed to prevent such a behavior with the default config values: org.quartz.jobStore.acquireTriggersWithinLock=false org.quartz.jobStore.txIsolationLevelSerializable=false

Hey @dstarcev , were you able to figure out how to fix these issues?

**Comment by abieleck** [comment]
I think I'm having the same issue:
```org.quartz.JobPersistenceException: Couldn't acquire next trigger: Cannot invoke "org.quartz.JobDetail.isConcurrentExectionDisallowed()" because "job" is null
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2923) ~[quartz-2.3.2.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2805) ~[quartz-2.3.2.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2803) ~[quartz-2.3.2.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3864) ~[quartz-2.3.2.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2802) ~[quartz-2.3.2.jar:na]
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:287) ~[quartz-2.3.2.jar:na]
Caused by: java.lang.NullPointerException: Cannot invoke "org.quartz.JobDetail.isConcurrentExectionDisallowed()" because "job" is null
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2875) ~[quartz-2.3.2.jar:na]
	... 5 common frames omitted
```

The jobs were scheduled at `2024-05-10T13:45:41.825+02:00 DEBUG 37084 --- [nio-8080-exec-1]`
They were cancelled at `2024-05-10T13:45:48.172+02:00 DEBUG 37084 --- [nio-8080-exec-3]`
Then there was the Quartz exception: `2024-05-10T13:45:48.193+02:00 ERROR 37084 --- [SchedulerThread]`

Jobs were cancelled using scheduler's deleteJob method

The database is PostgreSQL 15.2

This is what Quartz logs on app start:
```2024-05-10T13:45:23.545+02:00  INFO 37084 --- [           main] org.quartz.impl.StdSchedulerFactory      : Using default implementation for ThreadExecutor
2024-05-10T13:45:23.554+02:00  INFO 37084 --- [           main] org.quartz.core.SchedulerSignalerImpl    : Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2024-05-10T13:45:23.554+02:00  INFO 37084 --- [           main] org.quartz.core.QuartzScheduler          : Quartz Scheduler v.2.3.2 created.
2024-05-10T13:45:23.557+02:00  INFO 37084 --- [           main] o.s.s.quartz.LocalDataSourceJobStore     : Using db table-based data access locking (synchronization).
2024-05-10T13:45:23.559+02:00  INFO 37084 --- [           main] o.s.s.quartz.LocalDataSourceJobStore     : JobStoreCMT initialized.
2024-05-10T13:45:23.559+02:00  INFO 37084 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler meta-data: Quartz Scheduler (v2.3.2) 'quartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.springframework.scheduling.quartz.LocalDataSourceJobStore' - which supports persistence. and is not clustered.

2024-05-10T13:45:23.559+02:00  INFO 37084 --- [           main] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler 'quartzScheduler' initialized from an externally provided properties instance.
2024-05-10T13:45:23.559+02:00  INFO 37084 --- [           main] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler version: 2.3.2
2024-05-10T13:45:23.559+02:00  INFO 37084 --- [           main] org.quartz.core.QuartzScheduler          : JobFactory set to: org.springframework.scheduling.quartz.SpringBeanJobFactory@58178c5e
```

The configuration properties for quarts (it's a Spring Boot app) are:
```quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
```

Qurtz was added using `spring-boot-starter-quartz`, but It doesn't look like a spring boot issue. Spring Boo tversion is 3.2.5

**Comment by smcvb** [comment]
I've been experiencing the same issue as described, specifically when testing an application.
A schedule is created with Quartz and quickly canceled again, resulting in the following:

```txt
org.quartz.JobPersistenceException: Couldn't acquire next trigger: Cannot invoke "org.quartz.JobDetail.isConcurrentExectionDisallowed()" because "job" is null
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2923) ~[quartz-2.3.2.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2805) ~[quartz-2.3.2.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2803) ~[quartz-2.3.2.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3864) ~[quartz-2.3.2.jar:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2802) ~[quartz-2.3.2.jar:na]
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:287) ~[quartz-2.3.2.jar:na]
Caused by: java.lang.NullPointerException: Cannot invoke "org.quartz.JobDetail.isConcurrentExectionDisallowed()" because "job" is null
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2875) ~[quartz-2.3.2.jar:na]
	... 5 common frames omitted
```

I'm using _Java 17_,  _Kotlin 1.9.24_, _Spring Boot 3.3.2_, and PostgreSQL as a test container.
Perhaps the properties are helpful too, so here goes:

```yml
spring:
  datasource:
    url: jdbc:tc:postgresql:latest:///spring_boot_testcontainers?TC_DAEMON=true
    generate-unique-name: true
    hikari:
      minimum-idle: 1
  quartz:
    properties:
      org.quartz.scheduler.idleWaitTime: 5000
```

**Comment by fingerlink69** [comment]
Still experiencing the same issue here:

```
org.quartz.JobPersistenceException: Couldn't acquire next trigger: Cannot invoke "org.quartz.JobDetail.isConcurrentExectionDisallowed()" because "job" is null
             at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2924) ~[quartz-2.5.0-rc1.jar!/:2.5.0-rc1]
            at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2805) ~[quartz-2.5.0-rc1.jar!/:2.5.0-rc1]
            at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2803) ~[quartz-2.5.0-rc1.jar!/:2.5.0-rc1]
            at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3864) ~[quartz-2.5.0-rc1.jar!/:2.5.0-rc1]
            at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2802) ~[quartz-2.5.0-rc1.jar!/:2.5.0-rc1]
            at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:293) [quartz-2.5.0-rc1.jar!/:2.5.0-rc1]
Caused by: java.lang.NullPointerException: Cannot invoke "org.quartz.JobDetail.isConcurrentExectionDisallowed()" because "job" is null
            at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2875) ~[quartz-2.5.0-rc1.jar!/:2.5.0-rc1]
… 5 more
```

Is there any fix for this?
