### ISSUE TITLE
JobStoreSupport.triggersFired not using txValidator compensation logic

### ISSUE THREAD

**Issue by lahma** [quartz-scheduler/quartz#533]
I've been digging into [a .NET version's problem](https://github.com/quartznet/quartznet/issues/733) when database encounters a transient error, like a connectivity problem and thus should be retried. If you look at the code:

https://github.com/quartz-scheduler/quartz/blob/d42fb7770f287afbf91f6629d90e7698761ad7d8/quartz-core/src/main/java/org/quartz/impl/jdbcjobstore/JobStoreSupport.java#L2976-L3020 

All exceptions are caught in main txCallback and thus I don't see a way how the txValidator logic would ever be called. This will mean that this operation is not retried, unlike the acquireNextTriggers which allows exceptions to bubble up:

https://github.com/quartz-scheduler/quartz/blob/d42fb7770f287afbf91f6629d90e7698761ad7d8/quartz-core/src/main/java/org/quartz/impl/jdbcjobstore/JobStoreSupport.java#L2802-L2826

So before changing the behavior on .NET side I was hoping to get some feedback from Java side. Should the errors be allowed to bubble up or is the txValidator just redundant?

**Comment by lahma** [comment]
This is relevant and I would like to discuss whether it requires a fix.

**Comment by lahma** [comment]
This is relevant and I would like to discuss whether it requires a fix.

**Comment by fil512** [comment]
I'm seeing connection pool leaks through this stack.  Wonder if it's related?

2021-09-27 05:08:39.015 [admin_json.adminJsonEndpointJetty-1284] DEBUG R:7uJpuSm0o0kFtccm c.c.l.connection_pool_troubleshooting - 	at org.springframework.scheduling.quartz.LocalDataSourceJobStore$2.getConnection(LocalDataSourceJobStore.java:136)
2021-09-27 05:08:39.015 [admin_json.adminJsonEndpointJetty-1284] DEBUG R:7uJpuSm0o0kFtccm c.c.l.connection_pool_troubleshooting - 	at org.quartz.utils.DBConnectionManager.getConnection(DBConnectionManager.java:108)
2021-09-27 05:08:39.015 [admin_json.adminJsonEndpointJetty-1284] DEBUG R:7uJpuSm0o0kFtccm c.c.l.connection_pool_troubleshooting - 	at org.quartz.impl.jdbcjobstore.JobStoreCMT.getNonManagedTXConnection(JobStoreCMT.java:165)
2021-09-27 05:08:39.015 [admin_json.adminJsonEndpointJetty-1284] DEBUG R:7uJpuSm0o0kFtccm c.c.l.connection_pool_troubleshooting - 	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3854)
2021-09-27 05:08:39.015 [admin_json.adminJsonEndpointJetty-1284] DEBUG R:7uJpuSm0o0kFtccm c.c.l.connection_pool_troubleshooting - 	at org.quartz.impl.jdbcjobstore.JobStoreSupport.triggersFired(JobStoreSupport.java:2977)

**Comment by lahma** [comment]
This is relevant and I would like to discuss whether it requires a fix.

**Comment by lahma** [comment]
.

**Comment by lahma** [comment]
.

**Comment by lahma** [comment]
Oh for fuck's sake.

**Comment by vssarahan** [comment]
@lahma Is this problem relevant? if not, what solution did you implement? I'm currently using quartz 2.6.2 for .net, and would like to adopt an up-to-date solution.

**Comment by lahma** [comment]
This hasn't been addressed on either side to date.
