### ISSUE TITLE
Deadlock when using JNDI

### ISSUE THREAD

**Issue by johan-rodriguez** [quartz-scheduler/quartz#542]
Query below is causing deadlocks:

@P0 nvarchar(4000),@P1 nvarchar(4000),@P2 nvarchar(4000),@P3 nvarchar(4000))
UPDATE QRTZ_TRIGGERS SET TRIGGER_STATE = @P0 WHERE SCHED_NAME = 'HuPortalQuartzClusteredScheduler' AND TRIGGER_NAME = @P1 AND TRIGGER_GROUP = @P2 AND TRIGGER_STATE = @P3

I have reviewed the tables and they are properly indexed. These tables also have very few records. Deadlocks are caused because two processes access the same data and they are dependent on each other. SQL server chooses to kill one of the process and calls it a victim.

![image](https://user-images.githubusercontent.com/2343528/70438391-52ae8c00-1a53-11ea-9d0e-af93d79f89a9.png)

**Comment by feress** [comment]
We are facing the same issue on DB2 (10.5.5) with Quartz 2.3.0 and Spring Boot 1.5.18. The following snippet is extracted from DB2's deadlock monitor:

    Table of lock waited on: QRTZ_TRIGGERS
    Type of lock: Row
    Mode of lock: X   - Exclusive
    Mode application requested on lock: U   - Update
    Lock object name: 4
    Deadlocked Statement:
    Type     : Dynamic
    Operation: Execute
    Section  : 1
    Creator  : NULLID
    Package  : SYSSH200
    Cursor   : SQL_CURSH200C1
    Cursor was blocking: FALSE
    Text     : UPDATE QRTZ_TRIGGERS SET TRIGGER_STATE = ? WHERE SCHED_NAME = 'schedulerFactoryBean' AND JOB_NAME = ? AND JOB_GROUP = ? AND TRIGGER_STATE = ?

Quartz is configured to run in clustered mode (see config below). In total, there are 7 Batchjobs running every minute. Each Batchjob is annotated with `@DisallowConcurrentExecution`.

    org.quartz.scheduler.instanceName = MyClusteredScheduler
    org.quartz.scheduler.instanceId = AUTO
    
    # Configure ThreadPool
    org.quartz.threadPool.class = org.quartz.simpl.SimpleThreadPool
    org.quartz.threadPool.threadCount = 20
    org.quartz.threadPool.threadPriority = 5
     
    # Configure JobStore
    org.quartz.jobStore.class = org.quartz.impl.jdbcjobstore.JobStoreTX 
    org.quartz.jobStore.driverDelegateClass = org.quartz.impl.jdbcjobstore.StdJDBCDelegate
    org.quartz.jobStore.useProperties = false
    org.quartz.jobStore.dataSource = myDS
    org.quartz.jobStore.tablePrefix = QRTZ_
    org.quartz.jobStore.isClustered = true
    org.quartz.jobStore.clusterCheckinInterval = 5000
    org.quartz.jobStore.misfireThreshold = 10000
    
    # Configure Datasources  
    org.quartz.dataSource.myDS.driver = com.ibm.db2.jcc.DB2Driver
    org.quartz.dataSource.myDS.URL = jdbc:db2://localhost:50000/DB_NAME:currentSchema=SCHEMA_NAME;
    org.quartz.dataSource.myDS.user = user
    org.quartz.dataSource.myDS.password = secret
    org.quartz.dataSource.myDS.maxConnections = 5
    org.quartz.dataSource.myDS.validationQuery = SELECT 1 FROM SYSIBM.SYSDUMMY1

We tried setting `org.quartz.jobStore.acquireTriggersWithinLock = true` with no difference.

Are there any other solutions available, yet?

**Comment by StoneLYC** [comment]
We are facing the same issue on SQLSERVER2014  with Quartz 2.2.3 and Spring Boot 1.5.16:
'''
281. PreparedStatement.executeUpdate() FAILED! UPDATE QRTZ_TRIGGERS SET TRIGGER_STATE = 'PAUSED' WHERE SCHED_NAME = 'xxx-pro' 
AND JOB_NAME = 'xxx-sg-pro' AND JOB_GROUP = 'xxx-pro' 
AND TRIGGER_STATE = 'PAUSED_BLOCKED' 

com.microsoft.sqlserver.jdbc.SQLServerException: Transaction (Process ID 103) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:217)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1635)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:426)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:372)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:6276)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1794)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:184)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:159)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:315)
	at net.sf.log4jdbc.PreparedStatementSpy.executeUpdate(PreparedStatementSpy.java:1021)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.updateTriggerStatesForJobFromOtherState(StdJDBCDelegate.java:1520)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.triggeredJobComplete(JobStoreSupport.java:3107)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$45.executeVoid(JobStoreSupport.java:3059)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$VoidTransactionCallback.execute(JobStoreSupport.java:3719)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$VoidTransactionCallback.execute(JobStoreSupport.java:3717)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3803)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retryExecuteInNonManagedTXLock(JobStoreSupport.java:3758)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.triggeredJobComplete(JobStoreSupport.java:3055)
	at org.quartz.core.QuartzScheduler.notifyJobStoreJobComplete(QuartzScheduler.java:1804)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:269)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
'''

**Comment by jasminej82** [comment]
Still facinfìg this issue.
Quartz 2.3.2.
Any help?
