### ISSUE TITLE
Failure obtaining db row lock: UpdateLockRowSemaphore

### ISSUE THREAD

**Issue by Divs-Das** [quartz-scheduler/quartz#567]
Hi,

We are using quartz version 2.3.0. We are facing the below issue intermittently.

ERROR [36418-3432] [] QuartzSchedulerService - Failure obtaining db row lock: Lock wait timeout exceeded; try restarting transaction
org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: Lock wait timeout exceeded; try restarting transaction
org.quartz.impl.jdbcjobstore.UpdateLockRowSemaphore.executeSQL(UpdateLockRowSemaphore.java:103) ~[quartz-2.3.0.jar:?]
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113) ~[quartz-2.3.0.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreCMT.executeInLock(JobStoreCMT.java:238) ~[quartz-2.3.0.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1160) ~[quartz-2.3.0.jar:?]
	at org.quartz.core.QuartzScheduler.triggerJob(QuartzScheduler.java:1156) ~[quartz-2.3.0.jar:?]
	at org.quartz.impl.StdScheduler.triggerJob(StdScheduler.java:341) ~[quartz-2.3.0.jar:?]
	at org.quartz.impl.StdScheduler.triggerJob(StdScheduler.java:331) ~[quartz-2.3.0.jar:?]
.
.
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
	at sun.reflect.GeneratedConstructorAccessor704.newInstance(Unknown Source) ~[?:?]

From the quartz.properties in our project:
org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreCMT
org.quartz.jobStore.lockHandler.class=org.quartz.impl.jdbcjobstore.UpdateLockRowSemaphore
org.quartz.scheduler.batchTriggerAcquisitionMaxCount=50
org.quartz.jobStore.acquireTriggersWithinLock=true

I have checked the issue : https://github.com/quartz-scheduler/quartz/issues/268
This suggests to upgrade the quartz version, use StdRowLockSemaphore and to use the new parameters which are available from version 2.3.1
org.quartz.jobStore.lockHandler.maxRetry=7
org.quartz.jobStore.lockHandler.retryPeriod=3000

We are using MySQL database. Is there any other way to fix this issue other than by upgrading the jar and changing the semaphore to StdRowLockSemaphore.

Please help.

**Comment by JohnZhuA1** [comment]
I came cross the same issue. Not sure how to avoid this issue. 
database: mysql
version 2.3.1
org.quartz.jobStore.lockHandler.maxRetry=5
org.quartz.jobStore.lockHandler.retryPeriod=3000
