### ISSUE TITLE
Quartz JDBC with Postgres: obtainLock fails due to aborted connection  

### ISSUE THREAD

**Issue by merzbird** [quartz-scheduler/quartz#647]
Quartz version: **2.3.2**

Config
```
# Configure Main Scheduler Properties
org.quartz.scheduler.instanceName=App
org.quartz.scheduler.instanceId=AUTO

# Configure ThreadPool
org.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.threadCount=10
org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread=true

# Configure JobStore
org.quartz.jobStore.misfireThreshold=60000
org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
org.quartz.jobStore.useProperties=false
org.quartz.jobStore.dataSource=metadataDS
org.quartz.jobStore.tablePrefix=SCHEDULER_
org.quartz.jobStore.isClustered=true
org.quartz.jobStore.clusterCheckinInterval=20000
```

I have an application, which at start submits multiple jobs to Quartz concurrently. It requires locking on Quartz side and multiple connections try to obtain lock through `StdRowLockSemaphore`. Because it is a fresh start, `_locks` table is empty, so multiple threads try to insert lock row (e.g. `TRIGGER_ACCESS` lock). What this means that some of them will eventually fail, due to duplicate key constraint. My particular problem is that for Postgres JDBC connection in such situations are aborted automatically and `StdRowLockSemaphore`'s retry logic is useless, since the same connection is used all over again. 

See stacktrace:
```
Caused by: org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: ERROR: current transaction is aborted, commands ignored until end of transaction block [See nested exception: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block]
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:184)
	at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:113)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3857)
	at org.quartz.impl.jdbcjobstore.JobStoreTX.executeInLock(JobStoreTX.java:93)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeJobAndTrigger(JobStoreSupport.java:1063)
	at org.quartz.core.QuartzScheduler.scheduleJob(QuartzScheduler.java:855)
	at org.quartz.impl.StdScheduler.scheduleJob(StdScheduler.java:249)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1764)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at jdk.internal.reflect.GeneratedMethodAccessor295.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy70.executeQuery(Unknown Source)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:123)
	... 19 more
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "scheduler_locks_pkey"
  Detail: Key (sched_name, lock_name)=(APP, TRIGGER_ACCESS) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:124)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy70.executeUpdate(Unknown Source)
	at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:135)
	... 19 more
```

I have done some research and found that it could work if configuration option `quartz.jobStore.lockOnInsert` is set to `false`, but I am not really sure what consequences it may have. Javadoc is not particularly clear on that side
```
Whether or not to obtain locks when inserting new jobs/triggers.
Defaults to true, which is safest. Some databases (such as MS SQLServer) seem to require this to avoid deadlocks under high load, while others seem to do fine without. Settings this to false means isolation guarantees between job scheduling and trigger acquisition are entirely enforced by the database. Depending on the database and it's configuration this may cause unusual scheduling behaviors.
Setting this property to false will provide a significant performance increase during the addition of new jobs and triggers.
```  

It would be great if you could give some advice or create a fix for such problem. Thanks!

**Comment by wicked539** [comment]
+1 
We just ran into the same issue, it would be great if someone could clarify wether setting ```lockOnInsert``` to ```false``` is considered acceptable when using Quartz JDBC with Postgres.

**Comment by dmaiken** [comment]
For anyone running into this issue, I found that setting `org.quartz.jobStore.acquireTriggersWithinLock = true` worked. I didn't have to set `lockOnInsert` to `false` by doing this.

**Comment by evuki** [comment]
> For anyone running into this issue, I found that setting `org.quartz.jobStore.acquireTriggersWithinLock = true` worked. I didn't have to set `lockOnInsert` to `false` by doing this.

Is there any reasoning to be shared behind this? Why was setting `acquireTriggersWithinLock` to `true` beneficial instead of setting `lockOnInsert` to `false`? Now you're locking when both inserting and acquiring the triggers. What's actually happening here?

These are quite poorly explained in Quartz' docs. Not to mention the fact that it seems to be database client-specific (we're using Postgres as well and ran into same kind of problems).

**Comment by agvadrone** [comment]
The same issue. lockOnInsert = false does not help
