### ISSUE TITLE
MisfireHandler: Error handling misfires: Couldn't store trigger for job:Lock wait timeout exceeded

### ISSUE THREAD

**Issue by jiiehe** [quartz-scheduler/quartz#651]
2020-12-28 02:18:30.854  INFO [xwj-sys-quartz,,,] 756402 --- [_MisfireHandler] org.quartz.impl.jdbcjobstore.JobStoreTX  : Handling 1 trigger(s) that missed their scheduled fire-time.
2020-12-28 02:19:21.989 ERROR [xwj-sys-quartz,,,] 756402 --- [_MisfireHandler] org.quartz.impl.jdbcjobstore.JobStoreTX  : MisfireHandler: Error handling misfires: Couldn't store trigger 'projectStatusChange.projectStatusChangeTrigger' for 'projectStatusChange.projectStatusChangeJob' job:Lock wait timeout exceeded; try restarting transaction

org.quartz.JobPersistenceException: Couldn't store trigger 'projectStatusChange.projectStatusChangeTrigger' for 'projectStatusChange.projectStatusChangeJob' job:Lock wait timeout exceeded; try restarting transaction
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1228) ~[quartz-2.3.0.jar!/:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doUpdateOfMisfiredTrigger(JobStoreSupport.java:1042) ~[quartz-2.3.0.jar!/:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.recoverMisfiredJobs(JobStoreSupport.java:991) ~[quartz-2.3.0.jar!/:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doRecoverMisfires(JobStoreSupport.java:3249) ~[quartz-2.3.0.jar!/:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:3997) [quartz-2.3.0.jar!/:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.run(JobStoreSupport.java:4018) [quartz-2.3.0.jar!/:na]
Caused by: com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:123) ~[mysql-connector-java-8.0.15.jar!/:8.0.15]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.15.jar!/:8.0.15]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.15.jar!/:8.0.15]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:970) ~[mysql-connector-java-8.0.15.jar!/:8.0.15]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1109) ~[mysql-connector-java-8.0.15.jar!/:8.0.15]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1057) ~[mysql-connector-java-8.0.15.jar!/:8.0.15]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1377) ~[mysql-connector-java-8.0.15.jar!/:8.0.15]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1042) ~[mysql-connector-java-8.0.15.jar!/:8.0.15]
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:384) ~[c3p0-0.9.5.2.jar!/:0.9.5.2]
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.updateTrigger(StdJDBCDelegate.java:1222) ~[quartz-2.3.0.jar!/:na]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1223) ~[quartz-2.3.0.jar!/:na]
	... 5 common frames omitted

2020-12-28 02:19:36.994  INFO [xwj-sys-quartz,,,] 756402 --- [_MisfireHandler] org.quartz.impl.jdbcjobstore.JobStoreTX  : Handling 1 trigger(s) that missed their scheduled fire-time.
2020-12-28 02:20:42.858  INFO [xwj-sys-quartz,,,] 756402 --- [_MisfireHandler] org.quartz.impl.jdbcjobstore.JobStoreTX  : Handling 1 trigger(s) that missed their scheduled fire-time.
2020-12-28 02:21:11.387  INFO [xwj-sys-quartz,,,] 756402 --- [trap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2020-12-28 02:21:48.860  INFO [xwj-sys-quartz,,,] 756402 --- [_MisfireHandler] org.quartz.impl.jdbcjobstore.JobStoreTX  : Handling 3 trigger(s) that missed their scheduled fire-time.
2020-12-28 02:22:54.848  INFO [xwj-sys-quartz,,,] 756402 --- [_MisfireHandler] org.quartz.impl.jdbcjobstore.JobStoreTX  : Handling 3 trigger(s) that missed their scheduled fire-time.

**Comment by jiiehe** [comment]
Hey, guys, I'm wondering whether you guys meet the situation that I described like  my log. Before this error happens, the application works well, however, after this happened, all tasks shut down in 5 hours. and it just appears sometimes, not always. until now, I only meet it one time. I'm currently using 2.3.0 in my project. I'm really appreciate it if any of you guys could help me with this issue.

**Comment by jiiehe** [comment]
this is my configuration.
org.quartz.scheduler.instanceName=TaskQuartzScheduler
org.quartz.scheduler.instanceId=AUTO
org.quartz.scheduler.rmi.export=false
org.quartz.scheduler.rmi.proxy=false
org.quartz.scheduler.wrapJobExecutionInUserTransaction=false
org.quartz.threadPool.class = org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.threadCount = 50
org.quartz.threadPool.threadPriority = 5
org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread=false
org.quartz.jobStore.misfireThreshold = 60000
org.quartz.jobStore.class = org.quartz.impl.jdbcjobstore.JobStoreTX
org.quartz.jobStore.tablePrefix = QRTZ_
org.quartz.jobStore.dataSource = qzDS
org.quartz.jobStore.useProperties = true
org.quartz.jobStore.isClustered=true
org.quartz.dataSource.qzDS.driver = com.mysql.cj.jdbc.Driver
org.quartz.dataSource.qzDS.URL = jdbc:mysqurl
org.quartz.dataSource.qzDS.user = 
org.quartz.dataSource.qzDS.password = 
org.quartz.dataSource.qzDS.maxConnections = 30
org.quartz.dataSource.qzDS.validationQuery = SELECT 1 FROM DUAL
