### ISSUE TITLE
org.quartz.JobPersistenceException: Failure recovering jobs: Lock wait timeout exceeded; try restarting transaction

### ISSUE THREAD

**Issue by YH2012** [quartz-scheduler/quartz#759]
【Springboot 2.1.2.RELEASE + Quartz 2.3.0】isClustered: true
The error message is as follows：

2022-01-13 12:43:58.032 [QuartzScheduler_HOTEL_SCHEDULER-itri-test-011642045673120_ClusterManager] INFO  o.s.scheduling.quartz.LocalDataSourceJobStore:3629 - ClusterManager: detected 1 failed or restarted instances.
2022-01-13 12:43:58.032 [QuartzScheduler_HOTEL_SCHEDULER-itri-test-011642045673120_ClusterManager] INFO  o.s.scheduling.quartz.LocalDataSourceJobStore:3488 - ClusterManager: Scanning for instance "1-6f-zhangpengpeng1642044839638"'s failed in-progress jobs.
2022-01-13 12:44:49.104 [QuartzScheduler_HOTEL_SCHEDULER-itri-test-011642045673120_ClusterManager] ERROR o.s.scheduling.quartz.LocalDataSourceJobStore:3926 - ClusterManager: Error managing cluster: Failure recovering jobs: Lock wait timeout exceeded; try restarting transaction
org.quartz.JobPersistenceException: Failure recovering jobs: Lock wait timeout exceeded; try restarting transaction
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.clusterRecover(JobStoreSupport.java:3621)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3332)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3920)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3957)
Caused by: com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:123)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:974)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1113)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1381)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1046)
	at sun.reflect.GeneratedMethodAccessor251.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy667.executeUpdate(Unknown Source)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.deleteSchedulerState(StdJDBCDelegate.java:2961)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.clusterRecover(JobStoreSupport.java:3616)
	... 3 common frames omitted

**Comment by YH2012** [comment]
![image](https://user-images.githubusercontent.com/62928430/149444810-4b6f54dc-c4b3-4762-b2b5-8d0a24fe933b.png)

**Comment by YH2012** [comment]
Deadlock occurs when executing sql

DELETE FROM QRTZ_SCHEDULER_STATE WHERE SCHED_NAME = 'ZP_SCHEDULER' AND INSTANCE_NAME = '1-6f-zp1641891212424'
