### ISSUE TITLE
Something went wrong with quartz table lock.

### ISSUE THREAD

**Issue by icloudice** [quartz-scheduler/quartz#781]
we use quartz 2.3.2. and spring boot 2.5.3。

in a long time, quartz work normally. but one day, we found this error.

[2022-03-10 21:59:55,964] [WARN ] [xxxBaseScheduler_QuartzSchedulerThread] [AttributeRestoringConnectionInvocationHandler:restoreOriginalAtributes 144] Failed restore connection's original auto commit setting.
java.sql.SQLNonTransientConnectionException: (conn=76173715) (conn=76173715) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73) ~[mariadb-java-client-2.7.3.jar:?]
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:155) ~[mariadb-java-client-2.7.3.jar:?]
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:274) ~[mariadb-java-client-2.7.3.jar:?]
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:363) ~[mariadb-java-client-2.7.3.jar:?]
	at org.mariadb.jdbc.MariaDbStatement.executeUpdate(MariaDbStatement.java:627) ~[mariadb-java-client-2.7.3.jar:?]
	at org.mariadb.jdbc.MariaDbConnection.setAutoCommit(MariaDbConnection.java:727) ~[mariadb-java-client-2.7.3.jar:?]
	at com.alibaba.druid.filter.FilterChainImpl.connection_setAutoCommit(FilterChainImpl.java:738) ~[druid-1.2.3.jar:1.2.3]
	at com.alibaba.druid.filter.FilterAdapter.connection_setAutoCommit(FilterAdapter.java:986) ~[druid-1.2.3.jar:1.2.3]
	at com.alibaba.druid.filter.FilterChainImpl.connection_setAutoCommit(FilterChainImpl.java:733) ~[druid-1.2.3.jar:1.2.3]
	at com.alibaba.druid.filter.FilterAdapter.connection_setAutoCommit(FilterAdapter.java:986) ~[druid-1.2.3.jar:1.2.3]
	at com.alibaba.druid.filter.FilterChainImpl.connection_setAutoCommit(FilterChainImpl.java:733) ~[druid-1.2.3.jar:1.2.3]
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.setAutoCommit(ConnectionProxyImpl.java:429) ~[druid-1.2.3.jar:1.2.3]
	at com.alibaba.druid.pool.DruidPooledConnection.setAutoCommit(DruidPooledConnection.java:714) ~[druid-1.2.3.jar:1.2.3]
	at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.restoreOriginalAtributes(AttributeRestoringConnectionInvocationHandler.java:141) [quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.cleanupConnection(JobStoreSupport.java:3677) [quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3896) [quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retryExecuteInNonManagedTXLock(JobStoreSupport.java:3819) [quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.releaseAcquiredTrigger(JobStoreSupport.java:2940) [quartz-2.3.2.jar:?]
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:363) [quartz-2.3.2.jar:?]
Caused by: java.sql.SQLNonTransientConnectionException: (conn=76173715) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73) ~[mariadb-java-client-2.7.3.jar:?]
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:189) ~[mariadb-java-client-2.7.3.jar:?]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945) ~[mariadb-java-client-2.7.3.jar:?]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:249) ~[mariadb-java-client-2.7.3.jar:?]
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:357) ~[mariadb-java-client-2.7.3.jar:?]
	... 15 more
[2022-03-10 21:59:55,964] [ERROR] [xxxBaseScheduler_QuartzSchedulerThread] [DruidDataSource:recycle 2003] recyle error
java.sql.SQLNonTransientConnectionException: (conn=76173715) (conn=76173715) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73) ~[mariadb-java-client-2.7.3.jar:?]
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:155) ~[mariadb-java-client-2.7.3.jar:?]
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:274) ~[mariadb-java-client-2.7.3.jar:?]
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:363) ~[mariadb-java-client-2.7.3.jar:?]
	at org.mariadb.jdbc.MariaDbStatement.executeUpdate(MariaDbStatement.java:627) ~[mariadb-java-client-2.7.3.jar:?]
	at org.mariadb.jdbc.MariaDbConnection.setAutoCommit(MariaDbConnection.java:727) ~[mariadb-java-client-2.7.3.jar:?]
	at com.alibaba.druid.filter.FilterChainImpl.connection_setAutoCommit(FilterChainImpl.java:738) ~[druid-1.2.3.jar:1.2.3]
	at com.alibaba.druid.filter.FilterAdapter.connection_setAutoCommit(FilterAdapter.java:986) ~[druid-1.2.3.jar:1.2.3]
	at com.alibaba.druid.filter.FilterChainImpl.connection_setAutoCommit(FilterChainImpl.java:733) ~[druid-1.2.3.jar:1.2.3]
	at com.alibaba.druid.filter.FilterAdapter.connection_setAutoCommit(FilterAdapter.java:986) ~[druid-1.2.3.jar:1.2.3]
	at com.alibaba.druid.filter.FilterChainImpl.connection_setAutoCommit(FilterChainImpl.java:733) ~[druid-1.2.3.jar:1.2.3]
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.setAutoCommit(ConnectionProxyImpl.java:429) ~[druid-1.2.3.jar:1.2.3]
	at com.alibaba.druid.pool.DruidConnectionHolder.reset(DruidConnectionHolder.java:312) ~[druid-1.2.3.jar:1.2.3]
	at com.alibaba.druid.pool.DruidDataSource.recycle(DruidDataSource.java:1910) [druid-1.2.3.jar:1.2.3]
	at com.alibaba.druid.pool.DruidPooledConnection.recycle(DruidPooledConnection.java:325) [druid-1.2.3.jar:1.2.3]
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_recycle(FilterChainImpl.java:5049) [druid-1.2.3.jar:1.2.3]
	at com.alibaba.druid.filter.FilterAdapter.dataSource_releaseConnection(FilterAdapter.java:2750) [druid-1.2.3.jar:1.2.3]
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_recycle(FilterChainImpl.java:5045) [druid-1.2.3.jar:1.2.3]
	at com.alibaba.druid.filter.stat.StatFilter.dataSource_releaseConnection(StatFilter.java:674) [druid-1.2.3.jar:1.2.3]
	at com.alibaba.druid.filter.FilterChainImpl.dataSource_recycle(FilterChainImpl.java:5045) [druid-1.2.3.jar:1.2.3]
	at com.alibaba.druid.pool.DruidPooledConnection.close(DruidPooledConnection.java:268) [druid-1.2.3.jar:1.2.3]
	at org.springframework.jdbc.datasource.DataSourceUtils.doCloseConnection(DataSourceUtils.java:404) [spring-jdbc-5.3.9.jar:5.3.9]
	at org.springframework.jdbc.datasource.DataSourceUtils.doReleaseConnection(DataSourceUtils.java:391) [spring-jdbc-5.3.9.jar:5.3.9]
	at org.springframework.jdbc.datasource.DataSourceUtils.releaseConnection(DataSourceUtils.java:358) [spring-jdbc-5.3.9.jar:5.3.9]
	at org.springframework.scheduling.quartz.LocalDataSourceJobStore.closeConnection(LocalDataSourceJobStore.java:170) [spring-context-support-5.3.9.jar:5.3.9]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.cleanupConnection(JobStoreSupport.java:3678) [quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3896) [quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.retryExecuteInNonManagedTXLock(JobStoreSupport.java:3819) [quartz-2.3.2.jar:?]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.releaseAcquiredTrigger(JobStoreSupport.java:2940) [quartz-2.3.2.jar:?]
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:363) [quartz-2.3.2.jar:?]
Caused by: java.sql.SQLNonTransientConnectionException: (conn=76173715) Connection is closed
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73) ~[mariadb-java-client-2.7.3.jar:?]
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:189) ~[mariadb-java-client-2.7.3.jar:?]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1945) ~[mariadb-java-client-2.7.3.jar:?]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:249) ~[mariadb-java-client-2.7.3.jar:?]
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:357) ~[mariadb-java-client-2.7.3.jar:?]
	... 26 more

we first think our node lost connection with mysql. but our other function works well(read & write), while all the jobs are not work.  

so we try restart oure node and remove all the records in quartz table. we got those error.

**Sql Execute Exception : errorRow = 1, errorSql = delete from QRTZ_LOCKS;, errorMsg = (conn=76168326) Lock wait timeout exceeded; try restarting transaction**

we try find all the issues about this problems. like issue #268 . we do as they talk about,  it seems not works. 

one special point,  mysql run on arm arch. and mysql is self-development.

**Comment by icloudice** [comment]
We finally found wht`s the reason. we add some new configurations to connect database. connectTimeout=6000&socketTimeout=10000. we are sure that if a job acquire the lock, if it can not finish with the timeout, it will lose the connection with database, but the transaction will do run as well.  so we need remove the configurations.
