### ISSUE TITLE
RemoteScheduler client can not instantiate through Spring Boot.

### ISSUE THREAD

**Issue by jeff9finger** [quartz-scheduler/quartz#831]
Trying to user Spring Boot `SchedulerFactoryBean` to configure remote client for quartz cluster. But the client initialization fails

```java
Caused by: org.quartz.SchedulerException: Operation not supported for remote schedulers.
	at org.quartz.impl.RemoteScheduler.setJobFactory(RemoteScheduler.java:946)
	at org.springframework.scheduling.quartz.SchedulerFactoryBean.prepareScheduler(SchedulerFactoryBean.java:631)
	at org.springframework.scheduling.quartz.SchedulerFactoryBean.afterPropertiesSet(SchedulerFactoryBean.java:504)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	... 30 common frames omitted
```

I realize this may be a Spring issue, but am wondering:
# Is there an issue in quartz?
# If I am able to prevent `SchedulerFactoryBean.` from invoking `org.quartz.impl.RemoteScheduler.setJobFactory(RemoteScheduler.java:946)`, will the client operate correctly?

**Comment by jeff9finger** [comment]
I found that I don't need the RemoteScheduler at this time, so not blocking anything at the moment. But it does seem to be an issue.
