### ISSUE TITLE
JobStoreTX acquired connections are not sanitized for desired transaction isolation

### ISSUE THREAD

**Issue by veselov** [quartz-scheduler/quartz#921]
Ran into this with 2.3.2.

I have a (non-container managed) data source (tapping a Postgres DB)  that is shared among all the components inside (a J2EE web) application.
Some of the requests need to be handled in serialized transaction isolation, and as I have increased the amount of such requests, I started noticing random failures of Quartz to schedule jobs.

An example of a failure is attached below.

The root cause seems to be that Quartz doesn't sanitize the connections upon retrieval, unless transaction isolation is configured as "serializable" for Quartz (it's not in my case, nor I'm sure it'd be a good idea to do so).

There is this piece of code in `JobStoreSupport.getConnection()`:

```java
        try {
            if (!isDontSetAutoCommitFalse()) {
                conn.setAutoCommit(false);
            }

            if(isTxIsolationLevelSerializable()) {
                conn.setTransactionIsolation(Connection.TRANSACTION_SERIALIZABLE);
            }
        } catch (SQLException sqle) {
```

So, it will set the isolation to "serializable" if configured so, but won't set it to anything else if not.

I have two other users of the data source - OpenJPA and the application itself. I can make my code reset the connection state, but making OpenJPA do it is an entirely different feat.

I do see Quartz is being a good neighbor, and restoring the connection state back to what the state had been before it took the connection out, but I don't think that any component can have expectations about the configuration of the connection when it's being taken out of the data source (i.e., data source doesn't make any promises, or is expected to pre-configure the connections it vends out), if nothing else is because the connection needs to be "closed" to be released.

I think that the above `JobStore` code should call `conn.setTransactionIsolation(Connection.TRANSACTION_READ_COMMITTED)` as an "else" branch of the isolation check,
or at least have the property `org.quartz.jobStore.txIsolationLevelReadCommitted` be moved to the `JobStoreSupport` from `JobStoreCMT`, and have the code set corresponding isolation level if that property is configured.

I've worked around this by making my pool set "read committed" transaction isolation on every connection it issues.

Postgres failure:
```
        org.quartz.JobPersistenceException: Couldn't store trigger 'DEFAULT.CampaignImpactJob80C+qjZ2Oi4jjn7a46DvzL8YtTJi+XniAh35lw5X9Vs/USxBR+C2aWgkkrVEQ' for 'xxx.CampaignImpactJo
b' job:ERROR: could not serialize access due to read/write dependencies among transactions
  Detail: Reason code: Canceled on identification as a pivot, during write.
  Hint: The transaction might succeed if retried. [See nested exception: org.postgresql.util.PSQLException: ERROR: could not serialize access due to read/write dependencies among transactions
  Detail: Reason code: Canceled on identification as a pivot, during write.
  Hint: The transaction might succeed if retried.]
                at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1228)
                at org.quartz.impl.jdbcjobstore.JobStoreSupport$4.executeVoid(JobStoreSupport.java:1164)
                at org.quartz.impl.jdbcjobstore.JobStoreSupport$VoidTransactionCallback.execute(JobStoreSupport.java:3780)
                at org.quartz.impl.jdbcjobstore.JobStoreSupport$VoidTransactionCallback.execute(JobStoreSupport.java:3778)
                at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3864)
                at org.quartz.impl.jdbcjobstore.JobStoreTX.executeInLock(JobStoreTX.java:93)
                at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1160)
                at org.quartz.core.QuartzScheduler.scheduleJob(QuartzScheduler.java:901)
                at org.quartz.impl.StdScheduler.scheduleJob(StdScheduler.java:258)
                <application code>
        Caused by: org.postgresql.util.PSQLException: ERROR: could not serialize access due to read/write dependencies among transactions
  Detail: Reason code: Canceled on identification as a pivot, during write.
  Hint: The transaction might succeed if retried.
                at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
                at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
                at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
                at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
                at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
                at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
                at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:152)
                at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at com.company.api.impl.MyPooledConnection$StatementHandler.invoke(MyPooledConnection.java:427)
                at com.sun.proxy.$Proxy35.executeUpdate(Unknown Source)
                at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.insertTrigger(StdJDBCDelegate.java:1093)
                at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1225)

```

**Comment by jhouserizer** [comment]
Thanks for the report.  I suppose this fits somewhere in the grey area between bug and enhancement.

I'll note that the design/idea way back decades (!) ago now, was that the datasource provided to Quartz be set up either for it's exclusive use, or at least configured in a way that it gives quartz connections that are in the state expected.

I see however that this would be an improvement.  Will need to consider how to add that in such a way that it is sure not to break existing users who may not want that called on their connections.
