### ISSUE TITLE
No operations allowed after statement closed.

### ISSUE THREAD

**Issue by ivanmissu** [quartz-scheduler/quartz#930]
version  :  quartz 2.3.2
 org.quartz.JobPersistenceException: Couldn't acquire next trigger: No operations allowed after statement closed.
 	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2923)
 	at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2805)
 	at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2803)
 	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3864)
 	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2802)
 	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:287)
 Caused by: java.sql.SQLException: No operations allowed after statement closed.
 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897)
 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886)
 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
 	at com.mysql.jdbc.StatementImpl.checkClosed(StatementImpl.java:442)
 	at com.mysql.jdbc.StatementImpl.setLargeMaxRows(StatementImpl.java:2666)
 	at com.mysql.jdbc.StatementImpl.setMaxRows(StatementImpl.java:2372)
 	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.setMaxRows(NewProxyPreparedStatement.java:2071)
 	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectTriggerToAcquire(StdJDBCDelegate.java:2604)
 	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2844)
 	... 5 common frames omitted
how to fix it ??

@jhouserizer

**Comment by watari** [comment]
We have the similar problem on our project.

Library version: 2.3.2
DB: MySQL 8.0.33-25.1

Stack-trace of error:
```
[ERROR] (org.quartz.core.ErrorLogger):	An error occurred while scanning for the next triggers to fire.org.quartz.JobPersistenceException: Couldn't acquire next trigger: No operations allowed after statement closed.
 	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2923)
 	at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2805)
 	at org.quartz.impl.jdbcjobstore.JobStoreSupport$41.execute(JobStoreSupport.java:2803)
 	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3864)
 	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTriggers(JobStoreSupport.java:2802)
 	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:287)
 Caused by: java.sql.SQLException: No operations allowed after statement closed.
 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:82)
 	at com.mysql.cj.jdbc.StatementImpl.setLargeMaxRows(StatementImpl.java:2137)
 	at com.mysql.cj.jdbc.StatementImpl.setMaxRows(StatementImpl.java:1883)
 	at jdk.internal.reflect.GeneratedMethodAccessor99.invoke(Unknown Source)
 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
 	at com.mysql.cj.jdbc.ha.MultiHostConnectionProxy$JdbcInterfaceProxy.invoke(MultiHostConnectionProxy.java:107)
 	at com.mysql.cj.jdbc.ha.FailoverConnectionProxy$FailoverJdbcInterfaceProxy.invoke(FailoverConnectionProxy.java:98)
 	at jdk.proxy2/jdk.proxy2.$Proxy300.setMaxRows(Unknown Source)
 	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.setMaxRows(NewProxyPreparedStatement.java:2071)
 	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectTriggerToAcquire(StdJDBCDelegate.java:2604)
 	at org.quartz.impl.jdbcjobstore.JobStoreSupport.acquireNextTrigger(JobStoreSupport.java:2844)
 	... 5 common frames omitted
 Caused by: com.mysql.cj.exceptions.StatementIsClosedException: No operations allowed after statement closed.
 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
 	at com.mysql.cj.jdbc.StatementImpl.checkClosed(StatementImpl.java:336)
 	at com.mysql.cj.jdbc.StatementImpl.setLargeMaxRows(StatementImpl.java:2125)
 	... 15 common frames omitted
```

**Comment by siddharthgoel88** [comment]
We are also facing the same issue. Any guidance that we can have in this matter?

* MySQL 8.0.33
* Quartz 2.3.x (with SpringBoot 3.2)
