### ISSUE TITLE
Stable release download contains SNAPSHOT version

### ISSUE THREAD

**Issue by geertschuring** [quartz-scheduler/quartz#937]
I've downloaded the latest stable release from http://www.quartz-scheduler.org/downloads/ which points to http://www.quartz-scheduler.org/downloads/files/quartz-2.3.0-distribution.tar.gz

This file contains a directory named "quartz-2.3.0-**SNAPSHOT**"

**Comment by geertschuring** [comment]
I just discovered that the clustering examples don't work in this release. It seems the release is seriously flawed and requires attention. 

```
D:\Tools\quartz-2.3.0-SNAPSHOT\examples\example13>instance1.bat
[INFO] 12 jul. 11:27:02.598 a.m. main [org.quartz.impl.StdSchedulerFactory]
Using ConnectionProvider class 'org.quartz.utils.C3p0PoolingConnectionProvider' for data source 'myDS'

Exception in thread "main" org.quartz.SchedulerException: Could not initialize DataSource: myDS [See nested exception: org.quartz.SchedulerException: ConnectionProvider class 'org.quartz.utils.C3p0PoolingConnectionProvider' could not be instantiated. [See nested exception: java.lang.reflect.InvocationTargetException]]
        at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:1042)
        at org.quartz.impl.StdSchedulerFactory.getScheduler(StdSchedulerFactory.java:1559)
        at org.quartz.examples.example13.ClusterExample.run(ClusterExample.java:72)
        at org.quartz.examples.example13.ClusterExample.main(ClusterExample.java:208)
Caused by: org.quartz.SchedulerException: ConnectionProvider class 'org.quartz.utils.C3p0PoolingConnectionProvider' could not be instantiated. [See nested exception: java.lang.reflect.InvocationTargetException]
        at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:1032)
        ... 3 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:1030)
        ... 3 more
Caused by: java.lang.NoClassDefFoundError: com/mchange/v2/ser/Indirector
        at org.quartz.utils.C3p0PoolingConnectionProvider.initialize(C3p0PoolingConnectionProvider.java:186)
        at org.quartz.utils.C3p0PoolingConnectionProvider.<init>(C3p0PoolingConnectionProvider.java:131)
        ... 9 more
Caused by: java.lang.ClassNotFoundException: com.mchange.v2.ser.Indirector
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 11 more
```

I switched to version 2.2.3 and that fixes the problem. Release 2.3.0 is bugged.
