### ISSUE TITLE
triggers that are "stuck" in the "ACQUIRED" state

### ISSUE THREAD

**Issue by liushanshan6** [quartz-scheduler/quartz#95]
find problems in quartz-2.2.1.
after lost connection of database, some triggers never trigger again, and their state stuck in ACUQIRE.
 I had set org.quartz.jobStore.dontSetAutoCommitFalse=false, but it doesn't work.it is easy to reproduce this error, use some tool to make loop disconnection of mysql, after a few hours, it came up.
the error log:
2016-12-14 18:34:37,132 WARN [CronScheduler_QuartzSchedulerThread][ROOT][org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler 144] Failed restore connection's original auto commit setting.
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
at sun.reflect.GeneratedConstructorAccessor37.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
at com.mysql.jdbc.Util.getInstance(Util.java:360)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:924)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:870)
at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1232)
at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1225)
at com.mysql.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:4801)
at org.apache.commons.dbcp2.DelegatingConnection.setAutoCommit(DelegatingConnection.java:540)
at org.apache.commons.dbcp2.DelegatingConnection.setAutoCommit(DelegatingConnection.java:540)
at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.restoreOriginalAtributes(AttributeRestoringConnectionInvocationHandler.java:141)
at org.quartz.impl.jdbcjobstore.JobStoreSupport.cleanupConnection(JobStoreSupport.java:3600)
at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3819)
at org.quartz.impl.jdbcjobstore.JobStoreSupport.retryExecuteInNonManagedTXLock(JobStoreSupport.java:3742)
at org.quartz.impl.jdbcjobstore.JobStoreSupport.releaseAcquiredTrigger(JobStoreSupport.java:2865)
at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:346)

**Comment by jhouserizer** [comment]
It sounds like you are "corrupting" your DataSet (e.g. causing it to be full of closed connections)?

Have you set a sql validation statement for your datasource?  See: http://www.quartz-scheduler.org/documentation/quartz-2.2.x/configuration/ConfigDataSources.html

**Comment by liushanshan6** [comment]
In some case, the network is not stable, so it may unexpectedly lost db connections for a few seconds or several hours . After lost db connections and recovery, most jobs can trigger normally, but some jobs which should trigger at same time stuck in the "ACQUIRED" state. If I restart the application, these jobs trigger again.
When QuartzSchedulerThread release Acquired Trigger and it lost db connection, after recovery how does quartz  make sure that the state "ACQUIRE" can be changed to "EXECUTING" or others?
Maybe the problem is about the setting of datasource. I still have no idea about it.

**Comment by liushanshan6** [comment]
this is the setting of quartz.properties about datasource :
org.quartz.dataSource.cron.dataSourceId=crondb
org.quartz.dataSource.cron.connectionProvider.class=com.test.quartz.db.CronConnectionProvider
org.quartz.jobStore.dataSource=cron

crondb.mysql.connectionProperties = connectTimeout=10000;socketTimeout=30000
crondb.gauss.connectionProperties = loginTimeout=10;socketTimeout=30000

this is the datasource setting:
#pool config
crondb.maxActive = 5
crondb.maxIdle = 5
crondb.minIdle = 0
crondb.maxWait = 10000

#runtime config
crondb.testOnBorrow = true
crondb.testOnReturn = true
crondb.testWhileIdle = true

crondb.timeBetweenEvictionRunsMillis = 1800000
crondb.numTestsPerEvictionRun = 3
crondb.minEvictableIdleTimeMillis = 1800000

#clear abandoned config
crondb.removeAbandoned = true
crondb.removeAbandonedTimeout = 600

**Comment by liushanshan6** [comment]
finally, after I got the exception of disconnection from database, I restart scheduler to recover the job.

**Comment by ruochao** [comment]
@ShakespeareLiu did u figure out what's going on? I still see this issue on latest 2.3.2 release, and no solution found.

**Comment by papatil-mdsol** [comment]
@ShakespeareLiu  I am also facing this issue in 2.3.2 release. I have 10 Cron Trigger Scheduled for every 10 seconds, and its getting stuck in ACQUIRED state, showing PREV_FIRE_TIME and NEXT_FIRE_TIME same in the database.

**Comment by mircea-lemnaru-aera** [comment]
I also am seeing the same problem. I see that this issue was closed but cannot find any fix for this. Is there a workaround or some way to recover from this ? Thanks

**Comment by adarshnk** [comment]
This solution of setting socket timeout worked for me -  https://github.com/quartz-scheduler/quartz/issues/218#issuecomment-1501188951
